version: '3.4'

services:
  api:
    container_name: api
    image: ${DOCKER_REGISTRY-}netcoreboilerplate
    build:
      context: .
      dockerfile: src/NetCoreBoilerplate.Api/Dockerfile
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - default
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - default
    restart: unless-stopped

networks:
  default:
    driver: bridge

volumes:
    postgres:
